# Generated by Django 5.2.7 on 2025-10-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ragwebapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_response",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
