# Generated by Django 5.2.7 on 2025-10-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ragwebapp", "0002_chatmessage_is_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="message",
            field=models.CharField(default="", max_length=8192),
            preserve_default=False,
        ),
    ]
